# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-28 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step2', '0003_auto_20170125_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='journey_id',
            field=models.BigIntegerField(default=1),
        ),
    ]
